export const categories = [
  "Популярное",
  "Холодные закуски",
  "Салаты",
  "Супы",
  "Горячие закуски",
  "Горячие блюда",
  "Хинкали",
  "Шашлык",
  "Выпечка",
  "Гарниры",
  "Соусы",
  "Десерты",
  "Чай и кофе",
  "Напитки",
  "Пиво",
];

export const popularIds = new Set([
  "khinkali-classic",
  "adjaruli",
  "tabaka",
  "pkhali",
  "kharcho",
  "lamb-rack",
  "saamo-salad",
  "lobio",
]);

export const phone = "+74954650160";
export const whatsapp = "79035552126";
export const address = "Первомайская ул., 87, Москва";
export const mapUrl = "https://yandex.ru/maps/?text=Первомайская%20ул.%2087%20Москва";
export const adminPassword = "Xatuna$david12";

export const categoryImages = {
  "Холодные закуски": "/images/menu-pkhali.jpg",
  Салаты: "/images/menu-salad.jpg",
  Супы: "/images/menu-soup.jpg",
  "Горячие закуски": "/images/menu-hot.jpg",
  "Горячие блюда": "/images/menu-hot.jpg",
  Хинкали: "/images/menu-khinkali.jpg",
  Шашлык: "/images/menu-shashlik.jpg",
  Выпечка: "/images/menu-khachapuri.jpg",
  Гарниры: "/images/menu-hot.jpg",
  Соусы: "/images/menu-pkhali.jpg",
  Десерты: "/images/menu-dessert.jpg",
  "Чай и кофе": "/images/menu-drinks.jpg",
  Напитки: "/images/menu-drinks.jpg",
  Пиво: "/images/menu-drinks.jpg",
};

export const itemImages = {
  "khinkali-lamb": "/images/menu-khinkali.jpg",
  "khinkali-classic": "/images/menu-khinkali.jpg",
  "khinkali-cheese": "/images/menu-khinkali.jpg",
  "khinkali-beef": "/images/menu-khinkali.jpg",
  "khinkali-fry": "/images/menu-khinkali.jpg",
  imeruli: "/images/menu-khachapuri.jpg",
  lobiani: "/images/menu-khachapuri.jpg",
  spinach: "/images/menu-khachapuri.jpg",
  kubdari: "/images/menu-khachapuri.jpg",
  mchadi: "/images/menu-khachapuri.jpg",
  adjaruli: "/images/menu-khachapuri.jpg",
  megruli: "/images/menu-khachapuri.jpg",
  lavash: "/images/menu-khachapuri.jpg",
  pkhali: "/images/menu-pkhali.jpg",
  baklazhany: "/images/menu-pkhali.jpg",
  "lamb-rack": "/images/menu-shashlik.jpg",
  "lula-lamb": "/images/menu-shashlik.jpg",
  "lula-beef": "/images/menu-shashlik.jpg",
  "vegetable-skewer": "/images/menu-shashlik.jpg",
  "pork-rack": "/images/menu-shashlik.jpg",
  "pork-ribs": "/images/menu-shashlik.jpg",
  "pork-soft": "/images/menu-shashlik.jpg",
  trout: "/images/menu-shashlik.jpg",
  dorado: "/images/menu-shashlik.jpg",
  "assorti-skewer": "/images/menu-shashlik.jpg",
  "chicken-skewer": "/images/menu-shashlik.jpg",
  "lamb-soft": "/images/menu-shashlik.jpg",
  "lula-chicken": "/images/menu-shashlik.jpg",
};

export const menuItems = [
  { id: "pkhali", category: "Холодные закуски", name: "Ассорти из пхали", weight: "500 г", price: 980, description: "Пхали из шпината, свеклы, фасоли и рулет из баклажана", vegetarian: true },
  { id: "baklazhany", category: "Холодные закуски", name: "Баклажаны с орехами", weight: "200 г", price: 520, description: "Рулеты из баклажана с ореховой пастой, чесноком и специями", vegetarian: true },
  { id: "cheese", category: "Холодные закуски", name: "Ассорти из грузинских сыров", weight: "500 г", price: 990, description: "Сулугуни, чанах, имеретинский сыр" },
  { id: "tongue", category: "Холодные закуски", name: "Язык отварной с хреном", weight: "150 г", price: 620 },
  { id: "gurian-cabbage", category: "Холодные закуски", name: "Капуста по-гурийски", weight: "200 г", price: 380, vegetarian: true },
  { id: "pickles", category: "Холодные закуски", name: "Маринованные овощи", weight: "350 г", price: 520, vegetarian: true },
  { id: "herring", category: "Холодные закуски", name: "Сельдь с картофелем", weight: "200 г", price: 520 },

  { id: "saamo-salad", category: "Салаты", name: "Салат Саамо", weight: "300 г", price: 680, description: "Легкий фирменный салат с курицей, сыром и свежими овощами" },
  { id: "adjarian-salad", category: "Салаты", name: "Салат по-аджарски", weight: "300 г", price: 620, description: "Жареные баклажаны со сладким перцем, свежими томатами и зеленью", vegetarian: true },
  { id: "georgian-salad", category: "Салаты", name: "Салат по-грузински", weight: "300 г", price: 520, vegetarian: true, spicy: "mild" },
  { id: "georgian-nuts", category: "Салаты", name: "Салат по-грузински с орехами", weight: "300 г", price: 580, vegetarian: true, spicy: "mild" },
  { id: "caesar-chicken", category: "Салаты", name: "Цезарь с курицей", weight: "300 г", price: 650 },
  { id: "caesar-shrimp", category: "Салаты", name: "Цезарь с креветками", weight: "300 г", price: 680 },
  { id: "tbilisi", category: "Салаты", name: "Салат Тбилиси", weight: "300 г", price: 650 },
  { id: "mangal", category: "Салаты", name: "Мангал салат", weight: "200 г", price: 520, description: "Баклажан, болгарский перец и помидор с мангала, масло и зелень", vegetarian: true },
  { id: "greek", category: "Салаты", name: "Греческий салат", weight: "250 г", price: 580, vegetarian: true },

  { id: "kharcho", category: "Супы", name: "Харчо", weight: "300 г", price: 550 },
  { id: "borsch", category: "Супы", name: "Борщ", weight: "300 г", price: 450 },
  { id: "solyanka", category: "Супы", name: "Солянка", weight: "300 г", price: 550 },
  { id: "noodle", category: "Супы", name: "Куриный суп с лапшой", weight: "300 г", price: 450 },
  { id: "chikhirtma", category: "Супы", name: "Чихиртма", weight: "300 г", price: 480 },

  { id: "dolma", category: "Горячие закуски", name: "Долма", weight: "200 г", price: 580, description: "Фарш в виноградных листьях" },
  { id: "suluguni-ketsi", category: "Горячие закуски", name: "Сулугуни на кеци", weight: "300 г", price: 550, vegetarian: true },
  { id: "lobio", category: "Горячие закуски", name: "Лобио", weight: "300 г", price: 450, vegetarian: true, spicy: "mild" },
  { id: "kuchmachi", category: "Горячие закуски", name: "Кучмачи на кеци", weight: "250 г", price: 580, description: "Сердце, печень, легкие с луком, специями и гранатом", spicy: "mild" },
  { id: "mushroom-cheese", category: "Горячие закуски", name: "Грибы с сыром", weight: "250 г", price: 550, vegetarian: true },

  { id: "cutlets", category: "Горячие блюда", name: "Куриные котлеты с пюре", price: 580 },
  { id: "tabaka", category: "Горячие блюда", name: "Цыпленок табака с гарниром", weight: "1 шт + 100 г", price: 950 },
  { id: "ojakhuri-pork", category: "Горячие блюда", name: "Оджахури из свинины", weight: "350 г", price: 650, description: "Жаркое по-домашнему с картофелем, луком и специями" },
  { id: "ojakhuri-lamb", category: "Горячие блюда", name: "Оджахури из баранины", weight: "350 г", price: 680 },
  { id: "chkmeruli", category: "Горячие блюда", name: "Чкмерули", weight: "1 шт", price: 950, description: "Цыпленок в сливочно-чесночном соусе на кеци" },
  { id: "chashushuli", category: "Горячие блюда", name: "Чашушули", weight: "250 г", price: 650, description: "Тушеная телятина с луком и томатами на кеци" },

  { id: "khinkali-lamb", category: "Хинкали", name: "Хинкали из баранины", weight: "1 шт", price: 120, spicy: "mild" },
  { id: "khinkali-classic", category: "Хинкали", name: "Хинкали классические", weight: "1 шт", price: 120, spicy: "mild" },
  { id: "khinkali-cheese", category: "Хинкали", name: "Хинкали с сыром", weight: "1 шт", price: 100, vegetarian: true },
  { id: "khinkali-beef", category: "Хинкали", name: "Хинкали из говядины", weight: "1 шт", price: 120, spicy: "mild" },
  { id: "khinkali-fry", category: "Хинкали", name: "Обжарка хинкали", weight: "1 шт", price: 20 },

  { id: "lamb-rack", category: "Шашлык", name: "Баранья корейка", weight: "250 г", price: 1050 },
  { id: "lula-lamb", category: "Шашлык", name: "Люля-кебаб из баранины", weight: "220 г", price: 650 },
  { id: "lula-beef", category: "Шашлык", name: "Люля-кебаб из говядины", weight: "220 г", price: 620 },
  { id: "vegetable-skewer", category: "Шашлык", name: "Овощной шашлык", weight: "300 г", price: 850, vegetarian: true },
  { id: "pork-rack", category: "Шашлык", name: "Свиная корейка", weight: "220 г", price: 680 },
  { id: "pork-ribs", category: "Шашлык", name: "Свиные ребрышки", weight: "220 г", price: 650 },
  { id: "pork-soft", category: "Шашлык", name: "Свиная мякоть", weight: "220 г", price: 700 },
  { id: "trout", category: "Шашлык", name: "Форель", weight: "300 г", price: 1050 },
  { id: "dorado", category: "Шашлык", name: "Дорадо", weight: "300 г", price: 1050 },
  { id: "assorti-skewer", category: "Шашлык", name: "Ассорти из шашлыков", weight: "1500 г", price: 4500 },
  { id: "chicken-skewer", category: "Шашлык", name: "Куриный шашлык", weight: "220 г", price: 650 },
  { id: "lamb-soft", category: "Шашлык", name: "Баранья мякоть", weight: "220 г", price: 800 },
  { id: "lula-chicken", category: "Шашлык", name: "Люля-кебаб из курицы", weight: "220 г", price: 580 },

  { id: "imeruli", category: "Выпечка", name: "Хачапури по-имеретински", weight: "450 г", price: 620, vegetarian: true },
  { id: "lobiani", category: "Выпечка", name: "Лобиани", weight: "400 г", price: 500, description: "Начинка: красная фасоль", vegetarian: true },
  { id: "spinach", category: "Выпечка", name: "Хачапури со шпинатом", weight: "400 г", price: 700, vegetarian: true },
  { id: "kubdari", category: "Выпечка", name: "Кубдари", weight: "450 г", price: 700, description: "Мясная начинка с приправами" },
  { id: "mchadi", category: "Выпечка", name: "Мчади", weight: "2 шт", price: 200, vegetarian: true },
  { id: "adjaruli", category: "Выпечка", name: "Хачапури по-аджарски", weight: "350 г", price: 600, vegetarian: true },
  { id: "megruli", category: "Выпечка", name: "Хачапури по-мегрельски", weight: "500 г", price: 650, vegetarian: true, variants: "Цена уточняется по фото меню" },
  { id: "lavash", category: "Выпечка", name: "Лаваш", weight: "1 шт", price: 120, vegetarian: true },

  { id: "potato-mushroom", category: "Гарниры", name: "Картофель с грибами", weight: "200 г", price: 420, vegetarian: true },
  { id: "potato-onion", category: "Гарниры", name: "Картофель с луком", weight: "150 г", price: 320, vegetarian: true },
  { id: "boiled-potato", category: "Гарниры", name: "Картофель отварной", weight: "100 г", price: 320, vegetarian: true },
  { id: "puree", category: "Гарниры", name: "Пюре", weight: "100 г", price: 280, vegetarian: true },
  { id: "country-potato", category: "Гарниры", name: "Картофель по-деревенски", weight: "150 г", price: 350, vegetarian: true },
  { id: "fries", category: "Гарниры", name: "Картофель фри", weight: "150 г", price: 320, vegetarian: true },

  { id: "tkemali", category: "Соусы", name: "Ткемали", weight: "50 г", price: 150, vegetarian: true },
  { id: "satsebeli", category: "Соусы", name: "Сацебели", weight: "50 г", price: 120, vegetarian: true },
  { id: "adjika", category: "Соусы", name: "Аджика", weight: "40 г", price: 120, vegetarian: true, spicy: "hot" },
  { id: "narsharab", category: "Соусы", name: "Наршараб", weight: "50 г", price: 150, vegetarian: true },
  { id: "garlic", category: "Соусы", name: "Чесночный соус", weight: "50 г", price: 120, vegetarian: true },
  { id: "horseradish", category: "Соусы", name: "Хрен", weight: "50 г", price: 100, vegetarian: true },
  { id: "mustard", category: "Соусы", name: "Горчица", weight: "50 г", price: 100, vegetarian: true },
  { id: "sour-cream", category: "Соусы", name: "Сметана", weight: "50 г", price: 100, vegetarian: true },
  { id: "mayo", category: "Соусы", name: "Майонез", weight: "50 г", price: 100, vegetarian: true },

  { id: "pakhlava", category: "Десерты", name: "Пахлава", weight: "80 г", price: 250 },
  { id: "jam", category: "Десерты", name: "Варенье в ассортименте", weight: "100 г", price: 220, vegetarian: true },

  { id: "black-tea", category: "Чай и кофе", name: "Чай черный", weight: "400 мл", price: 350, description: "Зеленый, с чабрецом, с бергамотом" },
  { id: "green-tea", category: "Чай и кофе", name: "Чай зеленый", weight: "400 мл", price: 350, variants: "В меню также есть вариант за 450 ₽" },
  { id: "karkade", category: "Чай и кофе", name: "Чай каркаде", weight: "400 мл", price: 450 },
  { id: "big-teapot", category: "Чай и кофе", name: "Большой чайник", weight: "1,5 л", price: 450 },
  { id: "americano", category: "Чай и кофе", name: "Американо", weight: "100 мл", price: 250 },
  { id: "cappuccino", category: "Чай и кофе", name: "Капучино", weight: "100 мл", price: 250 },
  { id: "camomile", category: "Чай и кофе", name: "Чай ромашковый", weight: "400 мл", price: 450 },
  { id: "ginger", category: "Чай и кофе", name: "Чай имбирный", weight: "400 мл", price: 450 },
  { id: "linden", category: "Чай и кофе", name: "Чай липовый", weight: "400 мл", price: 450 },
  { id: "fruit-tea", category: "Чай и кофе", name: "Чай фруктовый", weight: "400 мл", price: 450 },
  { id: "turkish-small", category: "Чай и кофе", name: "Кофе по-турецки", weight: "100 мл", price: 150 },
  { id: "turkish-large", category: "Чай и кофе", name: "Кофе по-турецки", weight: "150 мл", price: 250 },

  { id: "mors-200", category: "Напитки", name: "Морс ягодный", weight: "200 мл", price: 150 },
  { id: "mors-500", category: "Напитки", name: "Морс ягодный", weight: "500 мл", price: 320 },
  { id: "mors-1000", category: "Напитки", name: "Морс ягодный", weight: "1000 мл", price: 650 },
  { id: "natakhtari", category: "Напитки", name: "Лимонад Натахтари", weight: "500 мл", price: 280 },
  { id: "coke", category: "Напитки", name: "Кока-кола", weight: "250 мл", price: 300 },
  { id: "borjomi", category: "Напитки", name: "Боржоми", weight: "500 мл", price: 300 },
  { id: "nabeglavi", category: "Напитки", name: "Набеглави", weight: "500 мл", price: 300 },
  { id: "water", category: "Напитки", name: "Вода негазированная", weight: "500 мл", price: 150 },
  { id: "juice-200", category: "Напитки", name: "Сок", weight: "200 мл", price: 150 },
  { id: "juice-500", category: "Напитки", name: "Сок", weight: "500 мл", price: 320 },
  { id: "juice-1000", category: "Напитки", name: "Сок", weight: "1000 мл", price: 650 },

  { id: "beer-filtered", category: "Пиво", name: "Пиво фильтрованное", weight: "500 мл", price: 300 },
  { id: "beer-unfiltered", category: "Пиво", name: "Пиво нефильтрованное", weight: "500 мл", price: 300 },
  { id: "beer-georgian", category: "Пиво", name: "Пиво грузинское", weight: "500 мл", price: 400 },
  { id: "croutons", category: "Пиво", name: "Гренки", price: 250 },
];
